/**
 * Full-App Multi-lingual Localization (English, Hindi, Odia)
 * Covers: Landing, CommandCenter, FarmerMode, CropAdvisory, RiskMap,
 *         Forecast, ClimateSignals, Historical, Explainability,
 *         Notifications, SystemStatus, Navbar, Footer, Sidebar, Auth
 */

const en = {
  // --- NAVBAR ---
  brand: "MoES • NCMRWF",
  brandSub: "Hyperlocal Monsoon Onset & Break Intelligence System",
  officerMode: "Officer Command Center",
  farmerMode: "Farmer Mode",
  signIn: "Sign In",
  signOut: "Sign Out",
  alerts: "Alerts",

  // --- SIDEBAR ---
  sidebarTitle: "Intelligence Modules",
  navLanding: "Home",
  navCommand: "Command Center",
  navRiskMap: "GIS Risk Map",
  navForecast: "7–30 Day Forecast",
  navClimate: "Climate Signals",
  navAdvisory: "Crop Advisory",
  navFarmer: "Farmer Mode",
  navNotifications: "Notification Center",
  navHistorical: "Historical Analysis",
  navExplain: "Explainable AI",
  navSystem: "System Health",

  // --- FOOTER ---
  footerLeft: "MoES / NCMRWF • Smart India Hackathon Working Prototype",
  footerRight: "Agro-Climatic Zone 11 (Odisha Coastal & Inland Plains) • FastAPI ML Service v1.2",

  // --- LANDING PAGE ---
  landingHero: "Hyperlocal Monsoon Intelligence & Decision Support",
  landingDesc: "AI-powered block-level monsoon onset & break prediction and crop decision support for climate-resilient agriculture across Indian farming blocks.",
  landingMinistry: "Ministry of Earth Sciences (MoES) • NCMRWF",
  landingPills: ["7–30 Day Probabilistic Outlook", "Block-Level Risk Mapping", "Climate Signal Integration (ENSO/IOD)", "Crop-Specific Sowing Advisories", "Multi-Lingual Farmer SMS/WhatsApp", "Explainable AI (SHAP Contributions)"],
  landingOpenCmd: "Open Command Center",
  landingExploreFarmer: "Explore Farmer Mode (Monsoon Saathi)",
  landingPipeline: "End-to-End Intelligence Pipeline",
  landingPipelineDesc: "From global atmospheric teleconnections to block-level risk and localized farmer advisories",
  landingSteps: [
    { title: "Global Climate", desc: "ENSO (+0.8), IOD (-0.4), MJO Phase 4 oceanic-atmospheric indices." },
    { title: "Regional Weather", desc: "Gridded numerical NWP data, IMD rainfall, satellite soil moisture." },
    { title: "AI ML Engine", desc: "FastAPI ML ensemble models probabilistic onset & break spells." },
    { title: "Hyperlocal Risk", desc: "GIS block polygons calibrated with risk levels." },
    { title: "Farmer Advisory", desc: "Crop-specific guidance in Odia, Hindi, English via SMS & WhatsApp." }
  ],
  landingGIS: "GIS Block Risk Mapping",
  landingGISDesc: "Explore interactive spatial layers for Onset, Break Spells, Heavy Rain, Soil Moisture, and Rainfall Anomaly across blocks.",
  landingGISLink: "Launch GIS Map",
  landingAdvisory: "Crop Advisory Engine",
  landingAdvisoryDesc: "Automated agronomic decision rules for Rice, Maize, Groundnut, Pulses, and Vegetables explaining exactly why each advice was triggered.",
  landingAdvisoryLink: "Generate Advisory",
  landingXAI: "Explainable AI (Why this Prediction?)",
  landingXAIDesc: "Transparent feature attribution breaking down how temperature anomaly, rainfall deficit, soil moisture, and ENSO signals drive risk scores.",
  landingXAILink: "View Feature Importance",

  // --- COMMAND CENTER ---
  cmdTitle: "Monsoon Command Center",
  cmdBadge: "Operational View",
  cmdHorizon: "Horizon",
  cmdOnset: "Monsoon Onset",
  cmdBreak: "Break / Dry Spell",
  cmdHeavyRain: "Heavy Rain (>65mm)",
  cmdConfidence: "Forecast Confidence",
  cmdFavorable: "Favorable Progression",
  cmdModerateWindow: "Moderate Window",
  cmdElevated: "Elevated Break Risk",
  cmdLowDry: "Low Dry Spell Risk",
  cmdHighInundation: "High Inundation Watch",
  cmdModConvection: "Moderate Convection",
  cmdCoupledModel: "Coupled Model Consensus",
  cmdHighConf: "HIGH CONF",
  cmdExpectedRain: "Expected Rainfall",
  cmdRainAnomaly: "Rainfall Anomaly",
  cmdClimatNormal: "Climatological Normal",
  cmdDeparture: "Departure from 30-yr IMD normal",
  cmdSoilMoisture: "Topsoil Moisture",
  cmdRootZone: "Root-zone moisture buffer",
  cmdSurfaceTemp: "Surface Temperature",
  cmdEvap: "Accelerated evapotranspiration",
  cmdAdvisoryActive: "Agro-Meteorological Advisory Active",
  cmdTargetCrop: "Target Crop",
  cmdSowingCaution: "Sowing Caution: Delay Rice Sowing by 5–7 Days",
  cmdAdvisoryDesc: "Break probability is elevated with low soil moisture. Avoid early dry-seeding without assured irrigation.",
  cmdQ1: "1. What will happen?",
  cmdQ1A: "Dry spell of 7–10 days expected in week 2.",
  cmdQ2: "2. Why this prediction?",
  cmdQ2A: "Rainfall deficit (-24%) + Warm ENSO (+0.8) + Low soil water.",
  cmdQ3: "3. What should farmer do?",
  cmdQ3A: "Delay transplanting 5-7 days & prepare backup irrigation ponds.",
  cmdOpenAdvisory: "Open Full Crop Advisory Engine",
  cmdWhyPrediction: "Why this prediction? (XAI)",
  cmdBroadcast: "Broadcast SMS / WhatsApp",
  cmdTimeline: "4-Week Multi-Period Progression Matrix",
  cmdFullTimeline: "Full Timeline Chart",
  cmdPeriod: "Period Horizon",
  cmdOnsetProb: "Onset Prob",
  cmdBreakRisk: "Break Risk",
  cmdHeavyRisk: "Heavy Rain",
  cmdExpectedRainTbl: "Expected Rain",
  cmdStatus: "Status",
  cmdFavOnset: "Favorable Onset",
  cmdDryBreak: "Dry Break Spell",
  cmdModStress: "Moderate Stress",
  cmdMonsoonRecovery: "Monsoon Recovery",
  cmdAlertsFeed: "Officer Alerts Feed",
  cmdActive: "Active",
  cmdAcknowledge: "Acknowledge",
  cmdAcknowledged: "Acknowledged",
  cmdGISMap: "Interactive GIS Risk Map",
  cmdGISDesc: "View Block Polygons",

  // --- RISK MAP ---
  riskTitle: "Hyperlocal GIS Risk Map",
  riskDesc: "Block-Level Geospatial Agro-Climate Risk Layers",
  riskSelectLayer: "Select Risk Layer:",
  riskLayerNames: ["Break / Dry Spell Risk", "Monsoon Onset Progression", "Heavy Rainfall Risk (>65mm)", "Rainfall Anomaly (% Departure)", "Topsoil Moisture Deficit"],
  riskInspect: "Inspecting Block",
  riskOnset: "Onset Prob",
  riskBreak: "Break Risk",
  riskHeavy: "Heavy Rain",
  riskExpected: "Expected (14d)",
  riskLegend: "Layer Classification Legend",
  riskLegendGreen: "Green: Favorable / Low Risk (<30%)",
  riskLegendYellow: "Yellow: Watch / Moderate Risk (31–60%)",
  riskLegendOrange: "Orange: High Risk (61–80%)",
  riskLegendRed: "Red: Very High Dry Spell Risk (81–100%)",
  riskLegendCyan: "Cyan: Heavy Rainfall Risk (>65mm)",
  riskZone: "Odisha (Zone 11)",

  // --- FORECAST ---
  fcTitle: "7–30 Day Probabilistic Forecast Outlook",
  fcDesc: "Monsoon Probability Timeline (0–30 Days)",
  fcPrecip: "Expected Precipitation & Probability",
  fcMatrix: "7–30 Day Period-by-Period Risk Matrix Table",
  fcTarget: "Target Location",
  fcTracking: "Tracking Onset vs Break Risk transition across the 30-day window",
  fcEstimate: "Estimated daily accumulation (mm) vs Rainfall Likelihood (%)",
  fcAggregated: "Aggregated meteorological parameters across 4 standard sub-seasonal horizons",
  fc7d: "7 Days Horizon",
  fc14d: "14 Days Horizon",
  fc21d: "21 Days Horizon",
  fc30d: "30 Days Horizon",
  fcPeriodRange: "Period Range",
  fcOnsetProb: "Onset Prob",
  fcBreakDry: "Break / Dry Spell",
  fcHeavyRain: "Heavy Rain (>65mm)",
  fcExpectedRain: "Expected Rain",
  fcRainProb: "Rainfall Likelihood",
  fcRegime: "Agro-Meteorological Regime",

  // --- CLIMATE SIGNALS ---
  clTitle: "Large-Scale Climate Signals & Teleconnections",
  clDesc: "Global oceanic and atmospheric oscillation indices modulating Indian monsoon intra-seasonal variability",
  clFeed: "MoES Assimilation Feed: Active",
  clENSO: "ENSO (Niño 3.4)",
  clENSOTitle: "Warm Anomaly (El Niño Watch)",
  clENSODesc: "Positive SST anomalies in central-eastern equatorial Pacific. Suppresses large-scale Indian monsoon Walker circulation.",
  clENSOImpact: "Tends to elevate break/dry-spell probabilities by 18-24%.",
  clIOD: "Indian Ocean Dipole (IOD)",
  clIODTitle: "Negative IOD",
  clIODDesc: "Cooler sea-surface temperatures in western Indian Ocean suppress moisture flux into the Bay of Bengal.",
  clIODImpact: "Reduces atmospheric moisture transport to coastal blocks.",
  clMJO: "Madden-Julian (MJO)",
  clMJOTitle: "Active (Phase 4 - Bay of Bengal)",
  clMJODesc: "Convective envelope active over Maritime Continent and Bay of Bengal.",
  clMJOImpact: "Provides short windows of localized convective rainfall buffering against macro subsidence.",
  clRegionalImpact: "Regional Impact:",
  clHowInfluence: "How Large-Scale Climate Signals Influence Local Block Predictions",
  clHowDesc: "Input features flow through the multi-layer ML ensemble to modulate block-level probabilities.",
  clFlowLabels: ["Suppresses Walker cell", "Weaker Bay of Bengal flux", "Short convective pulses", "Regional Weather", "Wind sheer & soil water", "Historical Climatology", "1991–2020 IMD Norms"],
  clFlowInput: "Fed into FastAPI Machine Learning Prediction Service (XGBoost / Calibrated RF)",
  clOutput: "Output: Hyperlocal Block Probabilistic Classification",

  // --- HISTORICAL ---
  histTitle: "Historical Monsoon Climatology (2021–2026)",
  histBaseline: "Baseline IMD Normal: 1,150 mm",
  histRainAnomaly: "Rainfall Anomaly (% Departure from Normal)",
  histRainAnomalyDesc: "Positive values indicate excess monsoon; negative values indicate drought/deficit stress",
  histDrySpell: "Longest Intra-Seasonal Dry Spell (Days)",
  histDrySpellDesc: "Consecutive rainless days during critical Kharif vegetative window",
  histArchive: "5-Year Historical Climatology Archive",
  histYear: "Year",
  histRainfall: "Seasonal Rainfall",
  histDeparture: "Departure",
  histOnsetDate: "Onset Date",
  histLongestDry: "Longest Dry Spell",
  histRegime: "Monsoon Regime Character",
  histRegimes: ["Near Normal with Late Break", "Timely & Favorable", "El Niño Influenced Deficit", "La Niña Modulated Surplus", "Neutral ENSO", "Active Dry Spell"],

  // --- EXPLAINABILITY ---
  xaiTitle: "Explainable AI (XAI) • Why This Prediction?",
  xaiSHAP: "SHAP Feature Attribution",
  xaiTarget: "Target Predicted Risk Metric",
  xaiBase: "Base Climatology",
  xaiMLDelta: "ML Delta",
  xaiWaterfall: "Feature Contribution Breakdown (SHAP Values)",
  xaiWaterfallDesc: "Percentage share of atmospheric, hydrological, and oceanic drivers elevating the risk score",
  xaiFeatures: [
    { name: "Recent Rainfall Deficit", desc: "Negative rainfall departure (-24%) indicates weak early monsoon convective buildup." },
    { name: "Temperature Anomaly", desc: "Surface temp elevated at 34.2°C (+2.8°C above normal), accelerating soil water depletion." },
    { name: "Low Soil Moisture", desc: "Topsoil volumetric water content is categorized as 'Low' (22% VWC)." },
    { name: "ENSO (Nino 3.4) Signal", desc: "Positive ENSO anomaly (+0.8°C) suppresses tropical Walker circulation over eastern India." },
    { name: "Historical Analog Pattern", desc: "Climatological analog matching shows 4 out of 5 similar years experienced 7+ day dry spells." },
    { name: "MJO Phase Modulation", desc: "MJO in Phase 4 provides intermittent showers buffering macro subsidence." }
  ],

  // --- NOTIFICATIONS ---
  notifTitle: "Farmer Notification & Alert Dispatch Center",
  notifDesc: "Multi-channel (SMS, WhatsApp, Voice OBD) dissemination gateway for block agricultural officers",
  notifRefresh: "Refresh Delivery Logs",
  notifSubscribers: "Total Subscribers",
  notifActive: "Active",
  notifDelivered: "Successfully Delivered",
  notifFailed: "Failed / Unreachable",
  notifTotalBroadcasts: "Total Broadcasts",
  notifAcross: "Across 10 Districts",
  notifCompose: "Compose & Broadcast Block Advisory",
  notifTarget: "Target",
  notifChannel: "Dissemination Channel:",
  notifChannels: ["WhatsApp & SMS", "SMS Only", "WhatsApp Only", "Voice OBD Broadcast"],
  notifMultiLang: "Multi-Lingual Broadcast Content:",
  notifSend: "Send Broadcast to",
  notifEstReach: "Estimated Reach: 5,240 registered farmers",
  notifHandset: "Farmer Handset Preview",
  notifDelivered2: "Delivered",
  notifLogs: "Recent Broadcast Logs & Audit Trail",
  notifBroadcastId: "Broadcast ID",
  notifLocation: "Location",
  notifChannel2: "Channel",
  notifSent: "Sent",
  notifDelivered3: "Delivered",
  notifFailed2: "Failed",
  notifStatus: "Status",

  // --- SYSTEM STATUS ---
  sysTitle: "System Health & Operational Status",
  sysDesc: "Real-time diagnostics of meteorological ingestion pipelines, ML services, and dispatch gateways",
  sysAllOk: "All Core Subsystems Operational",
  sysWeather: "Weather Data Ingestion",
  sysClimate: "Climate Signals",
  sysML: "ML Prediction Engine",
  sysLastRun: "Last Model Run",
  sysAvail: "AVAILABLE",
  sysOperational: "OPERATIONAL",
  sysTableTitle: "Subsystems & API Latency Telemetry",
  sysComponent: "Subsystem Component",
  sysType: "Type",
  sysStatus: "Status",
  sysLatency: "Response Latency",
  sysGovernance: "Prototype Integrity & Scientific Governance Notice",
  sysGovernanceDesc: "This system is an engineered working demonstration prototype developed for the Smart India Hackathon (SIH 2026) under the theme Agriculture, FoodTech & Rural Development.",

  // --- FARMER MODE ---
  fmAppTitle: "Monsoon Saathi",
  appTitle: "Monsoon Saathi",
  fmLocation: "Location",
  location: "Location",
  fmTodayAdvice: "Today's Agricultural Advice",
  todayAdvice: "Today's Agricultural Advice",
  fmSowingRisk: "Sowing Risk",
  sowingRisk: "Sowing Risk",
  fmDrySpellRisk: "Dry Spell Risk",
  drySpellRisk: "Dry Spell Risk",
  fmRainfallStatus: "Rainfall Outlook",
  rainfallStatus: "Rainfall Outlook",
  fmMyCrop: "My Crop",
  myCrop: "My Crop",
  fmForecast7d: "7-Day Outlook",
  forecast7d: "7-Day Outlook",
  fmAudioListen: "Listen to Advice",
  audioListen: "Listen to Advice",
  fmAudioPlaying: "Playing Audio...",
  audioPlaying: "Playing Audio...",
  fmCallHelpline: "Call Kisan Helpline (1800-180-1551)",
  callKisanHelpline: "Call Kisan Helpline (1800-180-1551)",
  fmCaution: "Do not sow rice immediately. Rainfall may remain irregular over the coming days. Keep irrigation available and monitor the next forecast update.",
  cautionMessage: "Do not sow rice immediately. Rainfall may remain irregular over the coming days. Keep irrigation available and monitor the next forecast update.",
  fmProceed: "Good rainfall continuity expected. You may proceed with nursery sowing and field preparation.",
  proceedMessage: "Good rainfall continuity expected. You may proceed with nursery sowing and field preparation.",
  fmDrainage: "Heavy rainfall alert! Clear drainage bunds immediately to protect standing nursery seedlings.",
  drainageMessage: "Heavy rainfall alert! Clear drainage bunds immediately to protect standing nursery seedlings.",
  fmIrrigation: "Dry spell developing. Arrange protective irrigation from borewells or farm ponds.",
  irrigationMessage: "Dry spell developing. Arrange protective irrigation from borewells or farm ponds.",
  high: "High",
  moderate: "Moderate",
  disclaimer: "Official MoES/IMD Data Stream",

  // --- AUTH ---
  authTitle: "MoES Monsoon Intel",
  authSubtitle: "Cloud alerts & weather updates sent to your mobile",
  authSignIn: "Sign In",
  authCreateAccount: "Create Account",
  authName: "Name",
  authPassword: "Password",
  authMobile: "Mobile Number",
  authPincode: "Area Pincode",
  authAutoDetect: "Auto Detect",
  authDetecting: "Detecting...",
  authNewFarmer: "New farmer?",
  authAlready: "Already registered?",
  authCreateOne: "Create Account",
  authSignin: "Sign in",
  authWeatherAlerts: "Weather alerts via SMS",
  authSecured: "MoES Secured",

  // --- CROP NAMES ---
  rice: "Rice (Paddy)",
  maize: "Maize",
  groundnut: "Groundnut",
  pulses: "Pulses",
  vegetables: "Vegetables",
  cotton: "Cotton",

  // --- COMMON ---
  mm: "mm",
  percent: "%",
  block: "Block",
  district: "District",
  days: "Days",
  listen: "Listen",
  playing: "Playing...",
};

const hi = {
  brand: "MoES • NCMRWF",
  brandSub: "अतिस्थानीय मानसून आरंभ और विराम बुद्धिमत्ता प्रणाली",
  officerMode: "कमांड सेंटर",
  farmerMode: "किसान मोड",
  signIn: "साइन इन",
  signOut: "साइन आउट",
  alerts: "अलर्ट",

  sidebarTitle: "बुद्धिमत्ता मॉड्यूल",
  navLanding: "होम",
  navCommand: "कमांड सेंटर",
  navRiskMap: "GIS जोखिम मानचित्र",
  navForecast: "7–30 दिन पूर्वानुमान",
  navClimate: "जलवायु संकेत",
  navAdvisory: "फसल सलाह",
  navFarmer: "किसान मोड",
  navNotifications: "सूचना केंद्र",
  navHistorical: "ऐतिहासिक विश्लेषण",
  navExplain: "व्याख्यात्मक AI",
  navSystem: "सिस्टम स्वास्थ्य",

  footerLeft: "MoES / NCMRWF • स्मार्ट इंडिया हैकाथॉन कार्यशील प्रोटोटाइप",
  footerRight: "कृषि-जलवायु क्षेत्र 11 (ओडिशा तटीय और आंतरिक मैदान) • FastAPI ML सेवा v1.2",

  landingHero: "अतिस्थानीय मानसून बुद्धिमत्ता और निर्णय समर्थन",
  landingDesc: "AI-संचालित ब्लॉक-स्तरीय मानसून आरंभ और विराम पूर्वानुमान और जलवायु-सक्षम कृषि के लिए फसल निर्णय समर्थन।",
  landingMinistry: "पृथ्वी विज्ञान मंत्रालय (MoES) • NCMRWF",
  landingPills: ["7–30 दिन संभाव्य दृष्टिकोण", "ब्लॉक-स्तरीय जोखिम मानचित्रण", "जलवायु संकेत एकीकरण (ENSO/OD)", "फसल-विशिष्ट बुवाई सलाह", "बहुभाषी किसान SMS/WhatsApp", "व्याख्यात्मक AI (SHAP)"],
  landingOpenCmd: "कमांड सेंटर खोलें",
  landingExploreFarmer: "किसान मोड देखें (मानसून साथी)",
  landingPipeline: "अंत-से-अंत बुद्धिमत्ता पाइपलाइन",
  landingPipelineDesc: "वैश्विक वायुमंडलीय दूरसंबंधों से ब्लॉक-स्तरीय जोखिम और स्थानीयकृत किसान सलाह तक",
  landingSteps: [
    { title: "वैश्विक जलवायु", desc: "ENSO (+0.8), IOD (-0.4), MJO चरण 4 महासागरीय-वायुमंडलीय सूचकांक।" },
    { title: "क्षेत्रीय मौसम", desc: "ग्रिडेड संख्यात्मक NWP डेटा, IMD वर्षा, उपग्रह मिट्टी की नमी।" },
    { title: "AI ML इंजन", desc: "FastAPI ML एन्सेम्बल मॉडल संभाव्य आरंभ और विराम काल।" },
    { title: "अतिस्थानीय जोखिम", desc: "GIS ब्लॉक बहुभुज जोखिम स्तरों के साथ अंशांकित।" },
    { title: "किसान सलाह", desc: "ओडिया, हिंदी, अंग्रेजी में फसल-विशिष्ट मार्गदर्शन।" }
  ],
  landingGIS: "GIS ब्लॉक जोखिम मानचित्रण",
  landingGISDesc: "आरंभ, विराम काल, भारी वर्षा, मिट्टी की नमी और वर्षा विसंगति के लिए इंटरैक्टिव स्थानिक परतें देखें।",
  landingGISLink: "GIS मानचित्र खोलें",
  landingAdvisory: "फसल सलाह इंजन",
  landingAdvisoryDesc: "धान, मक्का, मूंगफली, दालों और सब्जियों के लिए स्वचालित कृषि निर्णय नियम।",
  landingAdvisoryLink: "सलाह उत्पन्न करें",
  landingXAI: "व्याख्यात्मक AI (यह पूर्वानुमान क्यों?)",
  landingXAIDesc: "तापमान विसंगति, वर्षा घाटा, मिट्टी की नमी और ENSO संकेतों की विशेषता योगदान पारदर्शिता।",
  landingXAILink: "विशेषता महत्व देखें",

  cmdTitle: "मानसून कमांड सेंटर",
  cmdBadge: "संचालन दृश्य",
  cmdHorizon: "क्षितिज",
  cmdOnset: "मानसून आरंभ",
  cmdBreak: "विराम / शुष्क काल",
  cmdHeavyRain: "भारी वर्षा (>65mm)",
  cmdConfidence: "पूर्वानुमान विश्वसनीयता",
  cmdFavorable: "अनुकूल प्रगति",
  cmdModerateWindow: "मध्यम खिड़की",
  cmdElevated: "बढ़ा हुआ विराम जोखिम",
  cmdLowDry: "कम शुष्क काल जोखिम",
  cmdHighInundation: "उच्च जलप्लावन निगरानी",
  cmdModConvection: "मध्यम संवहन",
  cmdCoupledModel: "संयुक्त मॉडल सहमति",
  cmdHighConf: "उच्च विश्वसनीयता",
  cmdExpectedRain: "अनुमानित वर्षा",
  cmdRainAnomaly: "वर्षा विसंगति",
  cmdClimatNormal: "जलवायु सामान्य",
  cmdDeparture: "30-वर्षीय IMD सामान्य से प्रस्थान",
  cmdSoilMoisture: "मिट्टी की नमी",
  cmdRootZone: "जड़-क्षेत्र नमी बफर",
  cmdSurfaceTemp: "सतह तापमान",
  cmdEvap: "त्वरित वाष्पोत्सर्जन",
  cmdAdvisoryActive: "कृषि-मौसम विज्ञान सलाह सक्रिय",
  cmdTargetCrop: "लक्षित फसल",
  cmdSowingCaution: "बुवाई सावधानी: धान की बुवाई 5–7 दिन टालें",
  cmdAdvisoryDesc: "विराम संभावना बढ़ी हुई है, मिट्टी की नमी कम है। सिंचाई के बिना जल्दी बुवाई न करें।",
  cmdQ1: "1. क्या होगा?",
  cmdQ1A: "सप्ताह 2 में 7–10 दिन का शुष्क काल अपेक्षित।",
  cmdQ2: "2. यह पूर्वानुमान क्यों?",
  cmdQ2A: "वर्षा घाटा (-24%) + गर्म ENSO (+0.8) + कम मिट्टी जल।",
  cmdQ3: "3. किसान क्या करें?",
  cmdQ3A: "रोपण 5-7 दिन टालें और बैकअप सिंचाई तालाब तैयार करें।",
  cmdOpenAdvisory: "पूर्ण फसल सलाह इंजन खोलें",
  cmdWhyPrediction: "यह पूर्वानुमान क्यों? (XAI)",
  cmdBroadcast: "SMS / WhatsApp प्रसारण",
  cmdTimeline: "4-सप्ताह बहु-अवधि प्रगति मैट्रिक्स",
  cmdFullTimeline: "पूर्ण समयरेखा चार्ट",
  cmdPeriod: "अवधि क्षितिज",
  cmdOnsetProb: "आरंभ संभावना",
  cmdBreakRisk: "विराम जोखिम",
  cmdHeavyRisk: "भारी वर्षा",
  cmdExpectedRainTbl: "अनुमानित वर्षा",
  cmdStatus: "स्थिति",
  cmdFavOnset: "अनुकूल आरंभ",
  cmdDryBreak: "शुष्क विराम काल",
  cmdModStress: "मध्यम तनाव",
  cmdMonsoonRecovery: "मानसून पुनर्प्राप्ति",
  cmdAlertsFeed: "अधिकारी अलर्ट फ़ीड",
  cmdActive: "सक्रिय",
  cmdAcknowledge: "पुष्टि करें",
  cmdAcknowledged: "पुष्टि हो गई",
  cmdGISMap: "इंटरैक्टिव GIS जोखिम मानचित्र",
  cmdGISDesc: "ब्लॉक बहुभुज देखें",

  riskTitle: "अतिस्थानीय GIS जोखिम मानचित्र",
  riskDesc: "ब्लॉक-स्तरीय भौगोलिक कृषि-जलवायु जोखिम परतें",
  riskSelectLayer: "जोखिम परत चुनें:",
  riskLayerNames: ["विराम / शुष्क काल जोखिम", "मानसून आरंभ प्रगति", "भारी वर्षा जोखिम (>65mm)", "वर्षा विसंगति (% प्रस्थान)", "मिट्टी की नमी घाटा"],
  riskInspect: "निरीक्षण ब्लॉक",
  riskOnset: "आरंभ संभावना",
  riskBreak: "विराम जोखिम",
  riskHeavy: "भारी वर्षा",
  riskExpected: "अनुमानित (14d)",
  riskLegend: "परत वर्गीकरण लेजेंड",
  riskLegendGreen: "हरा: अनुकूल / कम जोखिम (<30%)",
  riskLegendYellow: "पीला: निगरानी / मध्यम जोखिम (31–60%)",
  riskLegendOrange: "नारंगी: उच्च जोखिम (61–80%)",
  riskLegendRed: "लाल: अत्यधिक शुष्क काल जोखिम (81–100%)",
  riskLegendCyan: "सियान: भारी वर्षा जोखिम (>65mm)",
  riskZone: "ओडिशा (क्षेत्र 11)",

  fcTitle: "7–30 दिन संभाव्य पूर्वानुमान दृष्टिकोण",
  fcDesc: "मानसून संभावना समयरेखा (0–30 दिन)",
  fcPrecip: "अनुमानित वर्षा और संभावना",
  fcMatrix: "7–30 दिन अवधि-दर-अवधि जोखिम मैट्रिक्स तालिका",
  fcTarget: "लक्षित स्थान",
  fcTracking: "30-दिनी खिड़की में आरंभ बनाम विराम जोखिम संक्रमण ट्रैकिंग",
  fcEstimate: "अनुमानित दैनिक संचयी (mm) बनाम वर्षा संभावना (%) ",
  fcAggregated: "4 मानक उप-मौसमी क्षितिजों में संकलित मौसम विज्ञान पैरामीटर",
  fc7d: "7 दिन क्षितिज",
  fc14d: "14 दिन क्षितिज",
  fc21d: "21 दिन क्षितिज",
  fc30d: "30 दिन क्षितिज",
  fcPeriodRange: "अवधि सीमा",
  fcOnsetProb: "आरंभ संभावना",
  fcBreakDry: "विराम / शुष्क काल",
  fcHeavyRain: "भारी वर्षा (>65mm)",
  fcExpectedRain: "अनुमानित वर्षा",
  fcRainProb: "वर्षा संभावना",
  fcRegime: "कृषि-मौसम विज्ञान व्यवस्था",

  clTitle: "बड़े पैमाने पर जलवायु संकेत और दूरसंबंध",
  clDesc: "भारतीय मानसून अंत-मौसमी परिवर्तनशीलता को संशोधित करने वाले वैश्विक महासागरीय और वायुमंडलीय दोलन सूचकांक",
  clFeed: "MoES आत्मसात फ़ीड: सक्रिय",
  clENSO: "ENSO (Niño 3.4)",
  clENSOTitle: "गर्म विसंगति (El Niño निगरानी)",
  clENSODesc: "मध्य-पूर्वी विषुवतीय प्रशांत में सकारात्मक SST विसंगतियाँ। भारतीय मानसून वॉकर परिसंचरण को दबाती हैं।",
  clENSOImpact: "विराम/शुष्क काल संभावनाओं को 18-24% बढ़ाता है।",
  clIOD: "हिंद महासागर डिपोल (IOD)",
  clIODTitle: "नकारात्मक IOD",
  clIODDesc: "पश्चिमी हिंद महासागर में ठंडे समुद्री सतह तापमान बंगाल की खाड़ी में नमी प्रवाह को दबाते हैं।",
  clIODImpact: "तटीय ब्लॉकों में वायुमंडलीय नमी परिवहन कम करता है।",
  clMJO: "मैडेन-जूलियन (MJO)",
  clMJOTitle: "सक्रिय (चरण 4 - बंगाल की खाड़ी)",
  clMJODesc: "सामुद्रिक महाद्वीप और बंगाल की खाड़ी पर संवहन आवरण सक्रिय।",
  clMJOImpact: "सूक्ष्म वर्षा की छोटी खिड़कियाँ प्रदान करता है।",
  clRegionalImpact: "क्षेत्रीय प्रभाव:",
  clHowInfluence: "बड़े पैमाने पर जलवायु संकेत स्थानीय ब्लॉक भविष्यवाणियों को कैसे प्रभावित करते हैं",
  clHowDesc: "इनपुट विशेषताएँ बहु-स्तरीय ML एन्सेम्बल से गुजरती हैं।",
  clFlowLabels: ["वॉकर कोशिका को दबाता है", "कमजोर बंगाल की खाड़ी प्रवाह", "छोटे संवहन पल्स", "क्षेत्रीय मौसम", "हवा की शीर्षता और मिट्टी जल", "ऐतिहासिक जलवायु विज्ञान", "1991–2020 IMD मानक"],
  clFlowInput: "FastAPI मशीन लर्निंग पूर्वानुमान सेवा में आपूर्ति",
  clOutput: "आउटपुट: अतिस्थानीय ब्लॉक संभाव्य वर्गीकरण",

  histTitle: "ऐतिहासिक मानसून जलवायु विज्ञान (2021–2026)",
  histBaseline: "आधारभूत IMD सामान्य: 1,150 mm",
  histRainAnomaly: "वर्षा विसंगति (% सामान्य से प्रस्थान)",
  histRainAnomalyDesc: "सकारात्मक मान अतिरिक्त मानसून दर्शाते हैं; नकारात्मक मान सूखा/घाटा तनाव दर्शाते हैं",
  histDrySpell: "सबसे लंबा अंत-मौसमी शुष्क काल (दिन)",
  histDrySpellDesc: "महत्वपूर्ण खरीफ वानस्पतिक अवधि के दौरान लगातार वर्षा-रहित दिन",
  histArchive: "5-वर्षीय ऐतिहासिक जलवायु विज्ञान संग्रह",
  histYear: "वर्ष",
  histRainfall: "मौसमी वर्षा",
  histDeparture: "प्रस्थान",
  histOnsetDate: "आरंभ तिथि",
  histLongestDry: "सबसे लंबा शुष्क काल",
  histRegime: "मानसून व्यवस्था चरित्र",
  histRegimes: ["विलंबित विराम के साथ निकट सामान्य", "समय पर और अनुकूल", "El Niño प्रभावित घाटा", "La Niña संशोधित अतिरिक्त", "तटस्थ ENSO", "सक्रिय शुष्क काल"],

  xaiTitle: "व्याख्यात्मक AI (XAI) • यह पूर्वानुमान क्यों?",
  xaiSHAP: "SHAP विशेषता अंशदान",
  xaiTarget: "लक्षित पूर्वानुमानित जोखिम मापदंड",
  xaiBase: "आधारभूत जलवायु विज्ञान",
  xaiMLDelta: "ML डेल्टा",
  xaiWaterfall: "विशेषता योगदान विघटन (SHAP मान)",
  xaiWaterfallDesc: "जोखिम स्कोर को बढ़ाने वाले वायुमंडलीय, जलीय और महासागरीय चालकों का प्रतिशत हिस्सा",
  xaiFeatures: [
    { name: "हालिया वर्षा घाटा", desc: "नकारात्मक वर्षा प्रस्थान (-24%) कमजोर प्रारंभिक मानसून संवहन निर्माण दर्शाता है।" },
    { name: "तापमान विसंगति", desc: "सतह तापमान 34.2°C (+2.8°C सामान्य से अधिक) तक बढ़ा हुआ।" },
    { name: "कम मिट्टी नमी", desc: "मिट्टी की मात्रात्मक जल सामग्री 'कम' (22% VWC) श्रेणी में है।" },
    { name: "ENSO (Nino 3.4) संकेत", desc: "सकारात्मक ENSO विसंगति (+0.8°C) पूर्वी भारत पर वॉकर परिसंचरण को दबाती है।" },
    { name: "ऐतिहासिक समान पैटर्न", desc: "जलवायु विज्ञान समान मिलान दर्शाता है कि 5 में से 4 समान वर्षों में 7+ दिन का शुष्क काल था।" },
    { name: "MJO चरण संशोधन", desc: "MJO चरण 4 में अंतरालिक वर्षा प्रदान करता है।" }
  ],

  notifTitle: "किसान सूचना और अलर्ट प्रसारण केंद्र",
  notifDesc: "ब्लॉक कृषि अधिकारियों के लिए बहु-चैनल (SMS, WhatsApp, Voice OBD) प्रसारण गेटवे",
  notifRefresh: "डिलीवरी लॉग रीफ्रेश करें",
  notifSubscribers: "कुल सदस्य",
  notifActive: "सक्रिय",
  notifDelivered: "सफलतापूर्वक डिलीवर",
  notifFailed: "विफल / अपहरणीय",
  notifTotalBroadcasts: "कुल प्रसारण",
  notifAcross: "10 जिलों में",
  notifCompose: "ब्लॉक सलाह लिखें और प्रसारित करें",
  notifTarget: "लक्ष्य",
  notifChannel: "प्रसारण चैनल:",
  notifChannels: ["WhatsApp और SMS", "केवल SMS", "केवल WhatsApp", "Voice OBD प्रसारण"],
  notifMultiLang: "बहुभाषी प्रसारण सामग्री:",
  notifSend: "को प्रसारण भेजें",
  notifEstReach: "अनुमानित पहुँच: 5,240 पंजीकृत किसान",
  notifHandset: "किसान हैंडसेट पूर्वावलोकन",
  notifDelivered2: "डिलीवर हो गया",
  notifLogs: "हालिया प्रसारण ल॑ग और ऑडिट ट्रेल",
  notifBroadcastId: "प्रसारण ID",
  notifLocation: "स्थान",
  notifChannel2: "चैनल",
  notifSent: "भेजा गया",
  notifDelivered3: "डिलीवर",
  notifFailed2: "विफल",
  notifStatus: "स्थिति",

  sysTitle: "सिस्टम स्वास्थ्य और संचालन स्थिति",
  sysDesc: "मौसम विज्ञान इन्जेस्टन पाइपलाइन, ML सेवाओं और प्रसारण गेटवे का वास्तविक-समय निदान",
  sysAllOk: "सभी मुख्य उप-प्रणालियाँ संचालन में",
  sysWeather: "मौसम डेटा इन्जेस्टन",
  sysClimate: "जलवायु संकेत",
  sysML: "ML पूर्वानुमान इंजन",
  sysLastRun: "अंतिम मॉडल रन",
  sysAvail: "उपलब्ध",
  sysOperational: "संचालन में",
  sysTableTitle: "उप-प्रणालियाँ और API विलंब टेलीमेट्री",
  sysComponent: "उप-प्रणाली घटक",
  sysType: "प्रकार",
  sysStatus: "स्थिति",
  sysLatency: "प्रतिक्रिया विलंब",
  sysGovernance: "प्रोटोटाइप अखंडता और वैज्ञानिक शासन सूचना",
  sysGovernanceDesc: "यह प्रणाली स्मार्ट इंडिया हैकाथॉन (SIH 2026) के लिए विकसित एक इंजीनियरिंग कार्यशील प्रदर्शन प्रोटोटाइप है।",

  fmAppTitle: "मानसून साथी",
  appTitle: "मानसून साथी",
  fmLocation: "स्थान",
  location: "स्थान",
  fmTodayAdvice: "आज की कृषि सलाह",
  todayAdvice: "आज की कृषि सलाह",
  fmSowingRisk: "बुवाई जोखिम",
  sowingRisk: "बुवाई जोखिम",
  fmDrySpellRisk: "शुष्क काल जोखिम",
  drySpellRisk: "शुष्क काल जोखिम",
  fmRainfallStatus: "वर्षा अनुमान",
  rainfallStatus: "वर्षा अनुमान",
  fmMyCrop: "मेरी फसल",
  myCrop: "मेरी फसल",
  fmForecast7d: "7-दिवसीय अनुमान",
  forecast7d: "7-दिवसीय अनुमान",
  fmAudioListen: "सलाह सुनें",
  audioListen: "सलाह सुनें",
  fmAudioPlaying: "सलाह सुनाई जा रही है...",
  audioPlaying: "सलाह सुनाई जा रही है...",
  fmCallHelpline: "किसान हेल्पलाइन पर कॉल करें (1800-180-1551)",
  callKisanHelpline: "किसान हेल्पलाइन पर कॉल करें (1800-180-1551)",
  fmCaution: "धान की बुवाई तुरंत न करें। आने वाले दिनों में वर्षा अनियमित रह सकती है। सिंचाई के साधन तैयार रखें।",
  cautionMessage: "धान की बुवाई तुरंत न करें। आने वाले दिनों में वर्षा अनियमित रह सकती है। सिंचाई के साधन तैयार रखें।",
  fmProceed: "अनुकूल वर्षा की संभावना है। आप धान की नर्सरी की बुवाई और खेत की तैयारी शुरू कर सकते हैं।",
  proceedMessage: "अनुकूल वर्षा की संभावना है। आप धान की नर्सरी की बुवाई और खेत की तैयारी शुरू कर सकते हैं।",
  fmDrainage: "भारी वर्षा की चेतावनी! खेत से अतिरिक्त जल निकासी की तुरंत व्यवस्था करें।",
  drainageMessage: "भारी वर्षा की चेतावनी! खेत से अतिरिक्त जल निकासी की तुरंत व्यवस्था करें।",
  fmIrrigation: "शुष्क दौर की संभावना। बोरवेल या तालाबों से सिंचाई का प्रबंध करें।",
  irrigationMessage: "शुष्क दौर की संभावना। बोरवेल या तालाबों से सिंचाई का प्रबंध करें।",
  high: "उच्च",
  moderate: "मध्यम",
  disclaimer: "आधिकारिक MoES/IMD डेटा स्ट्रीम",

  authTitle: "MoES मानसून इंटेल",
  authSubtitle: "आपके मोबाइल पर क्लाउड अलर्ट और मौसम अपडेट",
  authSignIn: "साइन इन",
  authCreateAccount: "खाता बनाएं",
  authName: "नाम",
  authPassword: "पासवर्ड",
  authMobile: "मोबाइल नंबर",
  authPincode: "क्षेत्र पिनकोड",
  authAutoDetect: "स्वतः पता लगाएं",
  authDetecting: "पता लगा रहे हैं...",
  authNewFarmer: "नए किसान?",
  authAlready: "पहले से पंजीकृत?",
  authCreateOne: "खाता बनाएं",
  authSignin: "साइन इन",
  authWeatherAlerts: "SMS के माध्यम से मौसम अलर्ट",
  authSecured: "MoES सुरक्षित",

  rice: "धान (चावल)",
  maize: "मक्का",
  groundnut: "मूंगफली",
  pulses: "दालें",
  vegetables: "सब्जियां",
  cotton: "कपास",

  mm: "mm",
  percent: "%",
  block: "ब्लॉक",
  district: "जिला",
  days: "दिन",
  listen: "सुनें",
  playing: "चल रहा है...",
};

const or = {
  brand: "MoES • NCMRWF",
  brandSub: "ଅତିସ୍ଥାନୀୟ ମୌସୁମୀ ଆରମ୍ଭ ଓ ବିରାମ ବୁଦ୍ଧିମତ୍ତା ପ୍ରଣାଳୀ",
  officerMode: "କମାଣ୍ଡ ସେଣ୍ଟର",
  farmerMode: "ଚାଷୀ ମୋଡ଼",
  signIn: "ସାଇନ୍ ଇନ୍",
  signOut: "ସାଇନ୍ ଆଉଟ୍",
  alerts: "ସତର୍କତା",

  sidebarTitle: "ବୁଦ୍ଧିମତ୍ତା ମଡ୍ୟୁଲ",
  navLanding: "ହୋମ୍",
  navCommand: "କମାଣ୍ଡ ସେଣ୍ଟର",
  navRiskMap: "GIS ବିପଦ ମାନଚିତ୍ର",
  navForecast: "୭–୩୦ ଦିନ ପୂର୍ବାନୁମାନ",
  navClimate: "ଜଳବାୟୁ ସଙ୍କେତ",
  navAdvisory: "ଫସଲ ପରାମର୍ଶ",
  navFarmer: "ଚାଷୀ ମୋଡ଼",
  navNotifications: "ସୂଚନା କେନ୍ଦ୍ର",
  navHistorical: "ଐତିହାସିକ ବିଶ୍ଳେଷଣ",
  navExplain: "ବ୍ୟାଖ୍ୟାତ୍ମକ AI",
  navSystem: "ସିଷ୍ଟମ୍ ସ୍ୱାସ୍ଥ୍ୟ",

  footerLeft: "MoES / NCMRWF • ସ୍ମାର୍ଟ ଇଣ୍ଡିଆ ହ୍ୟାକାଥନ୍ କାର୍ଯ୍ୟଶୀଳ ପ୍ରୋଟୋଟାଇପ୍",
  footerRight: "କୃଷି-ଜଳବାୟୁ ଅଞ୍ଚଳ ୧୧ (ଓଡ଼ିଶା ଉପକୂଳ ଓ ଅନ୍ତର୍ଦେଶୀୟ ସମତଳ) • FastAPI ML ସେବା v1.2",

  landingHero: "ଅତିସ୍ଥାନୀୟ ମୌସୁମୀ ବୁଦ୍ଧିମତ୍ତା ଓ ନିର୍ଣ୍ଣୟ ସମର୍ଥନ",
  landingDesc: "AI-ଚାଳିତ ବ୍ଲକ୍ ସ୍ତରୀୟ ମୌସୁମୀ ଆରମ୍ଭ ଓ ବିରାମ ପୂର୍ବାନୁମାନ ଏବଂ ଜଳବାୟୁ-ସକ୍ଷମ କୃଷି ପାଇଁ ଫସଲ ନିର୍ଣ୍ଣୟ ସମର୍ଥନ।",
  landingMinistry: "ପୃଥିବୀ ବିଜ୍ଞାନ ମନ୍ତ୍ରଣାଳୟ (MoES) • NCMRWF",
  landingPills: ["୭–୩୦ ଦିନ ସମ୍ଭାବ୍ୟ ଦୃଷ୍ଟିକୋଣ", "ବ୍ଲକ୍ ସ୍ତରୀୟ ବିପଦ ମାନଚିତ୍ରଣ", "ଜଳବାୟୁ ସଙ୍କେତ ଏକୀକରଣ (ENSO/OD)", "ଫସଲ-ନିର୍ଦ୍ଦିଷ୍ଟ ବୁଣା ପରାମର୍ଶ", "ବହୁଭାଷୀ ଚାଷୀ SMS/WhatsApp", "ବ୍ୟାଖ୍ୟାତ୍ମକ AI (SHAP)"],
  landingOpenCmd: "କମାଣ୍ଡ ସେଣ୍ଟର ଖୋଲନ୍ତୁ",
  landingExploreFarmer: "ଚାଷୀ ମୋଡ଼ ଦେଖନ୍ତୁ (ମୌସୁମୀ ସାଥୀ)",
  landingPipeline: "ଶେଷରୁ ଶେଷ ବୁଦ୍ଧିମତ୍ତା ପାଇପଲାଇନ୍",
  landingPipelineDesc: "ବୈଶ୍ୱିକ ବାୟୁମଣ୍ଡଳୀୟ ଦୂରସଂପର୍କରୁ ବ୍ଲକ୍ ସ୍ତରୀୟ ବିପଦ ଏବଂ ସ୍ଥାନୀୟ ଚାଷୀ ପରାମର୍ଶ ପର୍ଯ୍ୟନ୍ତ",
  landingSteps: [
    { title: "ବୈଶ୍ୱିକ ଜଳବାୟୁ", desc: "ENSO (+0.8), IOD (-0.4), MJO ପ୍ରାଣ ୪ ମହାସାଗରୀୟ-ବାୟୁମଣ୍ଡଳୀୟ ସୂଚକାଂକ।" },
    { title: "ଅଞ୍ଚଳୀୟ ପାଣିପାଗ", desc: "ଗ୍ରିଡେଡ୍ ସଂଖ୍ୟାତ୍ମକ NWP ତଥ୍ୟ, IMD ବର୍ଷା, ଉପଗ୍ରହ ମାଟି ଆର୍ଦ୍ରତା।" },
    { title: "AI ML ଇଞ୍ଜିନ୍", desc: "FastAPI ML ଏନ୍‌ସେମ୍ବଲ୍ ମଡେଲ୍ ସମ୍ଭାବ୍ୟ ଆରମ୍ଭ ଓ ବିରାମ କାଳ।" },
    { title: "ଅତିସ୍ଥାନୀୟ ବିପଦ", desc: "GIS ବ୍ଲକ୍ ବହୁଭୁଜ ବିପଦ ସ୍ତର ସହ କ୍ୟାଲିବ୍ରେଟେଡ୍।" },
    { title: "ଚାଷୀ ପରାମର୍ଶ", desc: "ଓଡ଼ିଆ, ହିନ୍ଦୀ, ଇଂରାଜୀରେ ଫସଲ-ନିର୍ଦ୍ଦିଷ୍ଟ ମାର୍ଗଦର୍ଶନ।" }
  ],
  landingGIS: "GIS ବ୍ଲକ୍ ବିପଦ ମାନଚିତ୍ରଣ",
  landingGISDesc: "ଆରମ୍ଭ, ବିରାମ କାଳ, ପ୍ରବଳ ବର୍ଷା, ମାଟି ଆର୍ଦ୍ରତା ଓ ବର୍ଷା ବିଚ୍ୟାସ ପାଇଁ ଇଣ୍ଟର୍ୟାକ୍ଟିଭ୍ ସ୍ଥାନିକ ସ୍ତର ଦେଖନ୍ତୁ।",
  landingGISLink: "GIS ମାନଚିତ୍ର ଖୋଲନ୍ତୁ",
  landingAdvisory: "ଫସଲ ପରାମର୍ଶ ଇଞ୍ଜିନ୍",
  landingAdvisoryDesc: "ଧାନ, ମକା, ଚିନାବାଦାମ, ଡାଲି ଓ ପରିବା ପାଇଁ ସ୍ୱୟଂଚାଳିତ କୃଷି ନିର୍ଣ୍ଣୟ ନିୟମ।",
  landingAdvisoryLink: "ପରାମର୍ଶ ଉତ୍ପାଦନ କରନ୍ତୁ",
  landingXAI: "ବ୍ୟାଖ୍ୟାତ୍ମକ AI (ଏହି ପୂର୍ବାନୁମାନ କାହିଁକି?)",
  landingXAIDesc: "ତାପମାନ ବିଚ୍ୟାସ, ବର୍ଷା ଅଭାବ, ମାଟି ଆର୍ଦ୍ରତା ଓ ENSO ସଙ୍କେତର ବିଶେଷତା ଯୋଗଦାନ ସ୍ୱଚ୍ଛତା।",
  landingXAILink: "ବିଶେଷତା ଗୁରୁତ୍ୱ ଦେଖନ୍ତୁ",

  cmdTitle: "ମୌସୁମୀ କମାଣ୍ଡ ସେଣ୍ଟର",
  cmdBadge: "ଅପରେସନାଲ୍ ଦୃଶ୍ୟ",
  cmdHorizon: "କ୍ଷିତିଜ",
  cmdOnset: "ମୌସୁମୀ ଆରମ୍ଭ",
  cmdBreak: "ବିରାମ / ଶୁଷ୍କ କାଳ",
  cmdHeavyRain: "ପ୍ରବଳ ବର୍ଷା (>65mm)",
  cmdConfidence: "ପୂର୍ବାନୁମାନ ନିର୍ଭରଯୋଗ୍ୟତା",
  cmdFavorable: "ଅନୁକୂଳ ଅଗ୍ରଗତି",
  cmdModerateWindow: "ମଧ୍ୟମ ଉଇଣ୍ଡୋ",
  cmdElevated: "ବୃଦ୍ଧି ପାଇଥିବା ବିରାମ ବିପଦ",
  cmdLowDry: "କମ୍ ଶୁଷ୍କ କାଳ ବିପଦ",
  cmdHighInundation: "ଉଚ୍ଚ ଜଳପ୍ଲାବନ ନଜର",
  cmdModConvection: "ମଧ୍ୟମ ସଂବହନ",
  cmdCoupledModel: "ଯୁଗ୍ମ ମଡେଲ୍ ସମ୍ମତି",
  cmdHighConf: "ଉଚ୍ଚ ନିର୍ଭରଯୋଗ୍ୟତା",
  cmdExpectedRain: "ଆଶା କରାଯାଉଥିବା ବର୍ଷା",
  cmdRainAnomaly: "ବର୍ଷା ବିଚ୍ୟାସ",
  cmdClimatNormal: "ଜଳବାୟୁ ସାଧାରଣ",
  cmdDeparture: "୩୦-ବର୍ଷୀୟ IMD ସାଧାରଣରୁ ପ୍ରସ୍ଥାନ",
  cmdSoilMoisture: "ମାଟି ଆର୍ଦ୍ରତା",
  cmdRootZone: "ମୂଳ-ଅଞ୍ଚଳ ଆର୍ଦ୍ରତା ବଫର",
  cmdSurfaceTemp: "ପୃଷ୍ଠ ତାପମାନ",
  cmdEvap: "ତ୍ୱରିତ ବାଷ୍ପୀଭବନ",
  cmdAdvisoryActive: "କୃଷି-ମୌସୁମ ବିଜ୍ଞାନ ପରାମର୍ଶ ସକ୍ରିୟ",
  cmdTargetCrop: "ଲକ୍ଷ୍ୟ ଫସଲ",
  cmdSowingCaution: "ବୁଣା ସାବଧାନ: ଧାନ ବୁଣା ୫–୭ ଦିନ ବିଳମ୍ବ କରନ୍ତୁ",
  cmdAdvisoryDesc: "ବିରାମ ସମ୍ଭାବନା ବୃଦ୍ଧି ପାଇଛି, ମାଟି ଆର୍ଦ୍ରତା କମ୍। ସିଞ୍ଚନ ବିନା ଶୀଘ୍ର ବୁଣା କରନ୍ତୁ ନାହିଁ।",
  cmdQ1: "୧. କ'ଣ ହେବ?",
  cmdQ1A: "ସପ୍ତାହ ୨ ରେ ୭–୧୦ ଦିନର ଶୁଷ୍କ କାଳ ଅପେକ୍ଷିତ।",
  cmdQ2: "୨. ଏହି ପୂର୍ବାନୁମାନ କାହିଁକି?",
  cmdQ2A: "ବର୍ଷା ଅଭାବ (-୨୪%) + ଉଷ୍ଣ ENSO (+0.8) + କମ୍ ମାଟି ଜଳ।",
  cmdQ3: "୩. ଚାଷୀ କ'ଣ କରିବେ?",
  cmdQ3A: "ରୋପଣ ୫-୭ ଦିନ ବିଳମ୍ବ କରନ୍ତୁ ଏବଂ ବ୍ୟାକଅପ୍ ସିଞ୍ଚନ ପୋଖରୀ ପ୍ରସ୍ତୁତ କରନ୍ତୁ।",
  cmdOpenAdvisory: "ସମ୍ପୂର୍ଣ୍ଣ ଫସଲ ପରାମର୍ଶ ଇଞ୍ଜିନ୍ ଖୋଲନ୍ତୁ",
  cmdWhyPrediction: "ଏହି ପୂର୍ବାନୁମାନ କାହିଁକି? (XAI)",
  cmdBroadcast: "SMS / WhatsApp ପ୍ରସାରଣ",
  cmdTimeline: "୪-ସପ୍ତାହ ବହୁ-ଅବଧି ଅଗ୍ରଗତି ମାଟ୍ରିକ୍ସ",
  cmdFullTimeline: "ସମ୍ପୂର୍ଣ୍ଣ ସମୟରେଖା ଚାର୍ଟ",
  cmdPeriod: "ଅବଧି କ୍ଷିତିଜ",
  cmdOnsetProb: "ଆରମ୍ଭ ସମ୍ଭାବନା",
  cmdBreakRisk: "ବିରାମ ବିପଦ",
  cmdHeavyRisk: "ପ୍ରବଳ ବର୍ଷା",
  cmdExpectedRainTbl: "ଆଶା କରାଯାଉଥିବା ବର୍ଷା",
  cmdStatus: "ସ୍ଥିତି",
  cmdFavOnset: "ଅନୁକୂଳ ଆରମ୍ଭ",
  cmdDryBreak: "ଶୁଷ୍କ ବିରାମ କାଳ",
  cmdModStress: "ମଧ୍ୟମ ଚାପ",
  cmdMonsoonRecovery: "ମୌସୁମୀ ପୁନରୁଦ୍ଧାର",
  cmdAlertsFeed: "ଅଧିକାରୀ ସତର୍କତା ଫିଡ୍",
  cmdActive: "ସକ୍ରିୟ",
  cmdAcknowledge: "ପୁଷ୍ଟି କରନ୍ତୁ",
  cmdAcknowledged: "ପୁଷ୍ଟି ହୋଇଗଲା",
  cmdGISMap: "ଇଣ୍ଟର୍ୟାକ୍ଟିଭ୍ GIS ବିପଦ ମାନଚିତ୍ର",
  cmdGISDesc: "ବ୍ଲକ୍ ବହୁଭୁଜ ଦେଖନ୍ତୁ",

  riskTitle: "ଅତିସ୍ଥାନୀୟ GIS ବିପଦ ମାନଚିତ୍ର",
  riskDesc: "ବ୍ଲକ୍ ସ୍ତରୀୟ ଭୌଗୋଳିକ କୃଷି-ଜଳବାୟୁ ବିପଦ ସ୍ତର",
  riskSelectLayer: "ବିପଦ ସ୍ତର ବାଛନ୍ତୁ:",
  riskLayerNames: ["ବିରାମ / ଶୁଷ୍କ କାଳ ବିପଦ", "ମୌସୁମୀ ଆରମ୍ଭ ଅଗ୍ରଗତି", "ପ୍ରବଳ ବର୍ଷା ବିପଦ (>65mm)", "ବର୍ଷା ବିଚ୍ୟାସ (% ପ୍ରସ୍ଥାନ)", "ମାଟି ଆର୍ଦ୍ରତା ଅଭାବ"],
  riskInspect: "ନିରୀକ୍ଷଣ ବ୍ଲକ୍",
  riskOnset: "ଆରମ୍ଭ ସମ୍ଭାବନା",
  riskBreak: "ବିରାମ ବିପଦ",
  riskHeavy: "ପ୍ରବଳ ବର୍ଷା",
  riskExpected: "ଆଶା (14d)",
  riskLegend: "ସ୍ତର ଶ୍ରେଣୀବିଭାଗ ଲେଜେଣ୍ଡ",
  riskLegendGreen: "ସବୁଜ: ଅନୁକୂଳ / କମ୍ ବିପଦ (<30%)",
  riskLegendYellow: "ହଳଦିଆ: ନଜର / ମଧ୍ୟମ ବିପଦ (୩୧–୬୦%)",
  riskLegendOrange: "କମଳା: ଉଚ୍ଚ ବିପଦ (୬୧–୮୦%)",
  riskLegendRed: "ଲାଲ୍: ଅତ୍ୟଧିକ ଶୁଷ୍କ କାଳ ବିପଦ (୮୧–୧୦୦%)",
  riskLegendCyan: "ସାଇନ୍: ପ୍ରବଳ ବର୍ଷା ବିପଦ (>65mm)",
  riskZone: "ଓଡ଼ିଶା (ଅଞ୍ଚଳ ୧୧)",

  fcTitle: "୭–୩୦ ଦିନ ସମ୍ଭାବ୍ୟ ପୂର୍ବାନୁମାନ ଦୃଷ୍ଟିକୋଣ",
  fcDesc: "ମୌସୁମୀ ସମ୍ଭାବନା ସମୟରେଖା (୦–୩୦ ଦିନ)",
  fcPrecip: "ଆଶା କରାଯାଉଥିବା ବର୍ଷା ଓ ସମ୍ଭାବନା",
  fcMatrix: "୭–୩୦ ଦିନ ଅବଧି-ଅନୁସାରେ ବିପଦ ମାଟ୍ରିକ୍ସ ତାଲିକା",
  fcTarget: "ଲକ୍ଷ୍ୟ ସ୍ଥାନ",
  fcTracking: "୩୦-ଦିନ ଉଇଣ୍ଡୋରେ ଆରମ୍ଭ ବନାମ ବିରାମ ବିପଦ ସଂକ୍ରମଣ ଟ୍ରାକିଂ",
  fcEstimate: "ଆଶା ଦୈନିକ ସଂଚୟ (mm) ବନାମ ବର୍ଷା ସମ୍ଭାବନା (%) ",
  fcAggregated: "୪ ମାନକ ଉପ-ମୌସୁମୀ କ୍ଷିତିଜରେ ସଂକଳିତ ମୌସୁମ ବିଜ୍ଞାନ ପାରାମିଟର",
  fc7d: "୭ ଦିନ କ୍ଷିତିଜ",
  fc14d: "୧୪ ଦିନ କ୍ଷିତିଜ",
  fc21d: "୨୧ ଦିନ କ୍ଷିତିଜ",
  fc30d: "୩୦ ଦିନ କ୍ଷିତିଜ",
  fcPeriodRange: "ଅବଧି ସୀମା",
  fcOnsetProb: "ଆରମ୍ଭ ସମ୍ଭାବନା",
  fcBreakDry: "ବିରାମ / ଶୁଷ୍କ କାଳ",
  fcHeavyRain: "ପ୍ରବଳ ବର୍ଷା (>65mm)",
  fcExpectedRain: "ଆଶା କରାଯାଉଥିବା ବର୍ଷା",
  fcRainProb: "ବର୍ଷା ସମ୍ଭାବନା",
  fcRegime: "କୃଷି-ମୌସୁମ ବିଜ୍ଞାନ ବ୍ୟବସ୍ଥା",

  clTitle: "ବଡ଼ ପରିସର ଜଳବାୟୁ ସଙ୍କେତ ଓ ଦୂରସଂପର୍କ",
  clDesc: "ଭାରତୀୟ ମୌସୁମୀ ଅନ୍ତ-ମୌସୁମୀ ପରିବର୍ତ୍ତନଶୀଳତାକୁ ସଂଶୋଧିତ କରୁଥିବା ବୈଶ୍ୱିକ ମହାସାଗରୀୟ ଓ ବାୟୁମଣ୍ଡଳୀୟ ଦୋଳନ ସୂଚକାଂକ",
  clFeed: "MoES ଆତ୍ମସାତ୍ ଫିଡ୍: ସକ୍ରିୟ",
  clENSO: "ENSO (Niño 3.4)",
  clENSOTitle: "ଉଷ୍ଣ ବିଚ୍ୟାସ (El Niño ନଜର)",
  clENSODesc: "ମଧ୍ୟ-ପୂର୍ବୀୟ ବିଷୁବତୀୟ ପ୍ରଶାନ୍ତରେ ସକାରାତ୍ମକ SST ବିଚ୍ୟାସ। ଭାରତୀୟ ମୌସୁମୀ ୱାକର ପରିସଂଚରଣକୁ ଦବାଏ।",
  clENSOImpact: "ବିରାମ/ଶୁଷ୍କ କାଳ ସମ୍ଭାବନାକୁ ୧୮-୨୪% ବୃଦ୍ଧି କରେ।",
  clIOD: "ହିନ୍ଦ ମହାସାଗର ଡିପୋଲ୍ (IOD)",
  clIODTitle: "ନକାରାତ୍ମକ IOD",
  clIODDesc: "ପଶ୍ଚିମ ହିନ୍ଦ ମହାସାଗରରେ ଥଣ୍ଡା ସମୁଦ୍ର ପୃଷ୍ଠ ତାପମାନ ବଙ୍ଗୋପସାଗରରେ ଆର୍ଦ୍ରତା ପ୍ରବାହକୁ ଦବାଏ।",
  clIODImpact: "ଉପକୂଳୀୟ ବ୍ଲକ୍‌ରେ ବାୟୁମଣ୍ଡଳୀୟ ଆର୍ଦ୍ରତା ପରିବହନ କମ୍ କରେ।",
  clMJO: "ମ୍ୟାଡେନ-ଜୁଲିଆନ୍ (MJO)",
  clMJOTitle: "ସକ୍ରିୟ (ପ୍ରାଣ ୪ - ବଙ୍ଗୋପସାଗର)",
  clMJODesc: "ସାମୁଦ୍ରିକ ମହାଦ୍ୱୀପ ଓ ବଙ୍ଗୋପସାଗର ଉପରେ ସଂବହନ ଆବରଣ ସକ୍ରିୟ।",
  clMJOImpact: "ସୂକ୍ଷ୍ମ ବର୍ଷାର ସ୍ଥାନୀୟ ଖିଡ଼କୀ ପ୍ରଦାନ କରେ।",
  clRegionalImpact: "ଅଞ୍ଚଳୀୟ ପ୍ରଭାବ:",
  clHowInfluence: "ବଡ଼ ପରିସର ଜଳବାୟୁ ସଙ୍କେତ ସ୍ଥାନୀୟ ବ୍ଲକ୍ ଭବିଷ୍ୟବାଣୀକୁ କିପରି ପ୍ରଭାବିତ କରେ",
  clHowDesc: "ଇନ୍‌ପୁଟ୍ ବିଶେଷତା ବହୁ-ସ୍ତରୀୟ ML ଏନ୍‌ସେମ୍ବଲ୍ ମଧ୍ୟ ଦେଇ ଯାଏ।",
  clFlowLabels: ["ୱାକର କୋଷିକା ଦବାଏ", "ଦୁର୍ବଳ ବଙ୍ଗୋପସାଗର ପ୍ରବାହ", "ଛୋଟ ସଂବହନ ପଲ୍ସ", "ଅଞ୍ଚଳୀୟ ପାଣିପାଗ", "ବାତାବରଣ ଶୀର୍ଷତା ଓ ମାଟି ଜଳ", "ଐତିହାସିକ ଜଳବାୟୁ ବିଜ୍ଞାନ", "୧୯୯୧–୨୦୨୦ IMD ମାନକ"],
  clFlowInput: "FastAPI ମେସିନ୍ ଲର୍ଣ୍ଣିଂ ପୂର୍ବାନୁମାନ ସେବାରେ ଯୋଗାଣ",
  clOutput: "ଆଉଟପୁଟ୍: ଅତିସ୍ଥାନୀୟ ବ୍ଲକ୍ ସମ୍ଭାବ୍ୟ ଶ୍ରେଣୀବିଭାଗ",

  histTitle: "ଐତିହାସିକ ମୌସୁମୀ ଜଳବାୟୁ ବିଜ୍ଞାନ (୨୦୨୧–୨୦୨୬)",
  histBaseline: "ଆଧାରଭୂତ IMD ସାଧାରଣ: ୧,୧୫୦ mm",
  histRainAnomaly: "ବର୍ଷା ବିଚ୍ୟାସ (% ସାଧାରଣରୁ ପ୍ରସ୍ଥାନ)",
  histRainAnomalyDesc: "ସକାରାତ୍ମକ ମୂଲ୍ୟ ଅତିରିକ୍ତ ମୌସୁମୀ ଦର୍ଶାଏ; ନକାରାତ୍ମକ ମୂଲ୍ୟ ଖରା/ଅଭାବ ଚାପ ଦର୍ଶାଏ",
  histDrySpell: "ଦୀର୍ଘତମ ଅନ୍ତ-ମୌସୁମୀ ଶୁଷ୍କ କାଳ (ଦିନ)",
  histDrySpellDesc: "ଗୁରୁତ୍ୱପୂର୍ଣ୍ଣ ଖରିଫ୍ ବୃଦ୍ଧି ଅବଧି ସମୟରେ ଲଗାତାର ବର୍ଷା-ରହିତ ଦିନ",
  histArchive: "୫-ବର୍ଷୀୟ ଐତିହାସିକ ଜଳବାୟୁ ବିଜ୍ଞାନ ସଂଗ୍ରହ",
  histYear: "ବର୍ଷ",
  histRainfall: "ମୌସୁମୀ ବର୍ଷା",
  histDeparture: "ପ୍ରସ୍ଥାନ",
  histOnsetDate: "ଆରମ୍ଭ ତିଥି",
  histLongestDry: "ଦୀର୍ଘତମ ଶୁଷ୍କ କାଳ",
  histRegime: "ମୌସୁମୀ ବ୍ୟବସ୍ଥା ଚରିତ୍ର",
  histRegimes: ["ବିଳମ୍ବିତ ବିରାମ ସହ ନିକଟ ସାଧାରଣ", "ସମୟରେ ଓ ଅନୁକୂଳ", "El Niño ପ୍ରଭାବିତ ଅଭାବ", "La Niña ସଂଶୋଧିତ ଅତିରିକ୍ତ", "ତଟସ୍ଥ ENSO", "ସକ୍ରିୟ ଶୁଷ୍କ କାଳ"],

  xaiTitle: "ବ୍ୟାଖ୍ୟାତ୍ମକ AI (XAI) • ଏହି ପୂର୍ବାନୁମାନ କାହିଁକି?",
  xaiSHAP: "SHAP ବିଶେଷତା ଯୋଗଦାନ",
  xaiTarget: "ଲକ୍ଷ୍ୟ ପୂର୍ବାନୁମାନିତ ବିପଦ ମାପଦଣ୍ଡ",
  xaiBase: "ଆଧାରଭୂତ ଜଳବାୟୁ ବିଜ୍ଞାନ",
  xaiMLDelta: "ML ଡେଲ୍ଟା",
  xaiWaterfall: "ବିଶେଷତା ଯୋଗଦାନ ବିଶ୍ଳେଷଣ (SHAP ମୂଲ୍ୟ)",
  xaiWaterfallDesc: "ବିପଦ ସ୍କୋର୍ ବୃଦ୍ଧି କରୁଥିବା ବାୟୁମଣ୍ଡଳୀୟ, ଜଳଜ ଓ ମହାସାଗରୀୟ ଚାଳକର ଶତକଡା ଅଂଶ",
  xaiFeatures: [
    { name: "ସାମ୍ପ୍ରତିକ ବର୍ଷା ଅଭାବ", desc: "ନକାରାତ୍ମକ ବର୍ଷା ପ୍ରସ୍ଥାନ (-୨୪%) ଦୁର୍ବଳ ପ୍ରାରମ୍ଭିକ ମୌସୁମୀ ସଂବହନ ନିର୍ମାଣ ଦର୍ଶାଏ।" },
    { name: "ତାପମାନ ବିଚ୍ୟାସ", desc: "ପୃଷ୍ଠ ତାପମାନ ୩୪.୨°C (+୨.୮°C ସାଧାରଣଠାରୁ ଅଧିକ) ପର୍ଯ୍ୟନ୍ତ ବୃଦ୍ଧି ପାଇଛି।" },
    { name: "କମ୍ ମାଟି ଆର୍ଦ୍ରତା", desc: "ମାଟିର ପରିମାଣାତ୍ମକ ଜଳ ସାମଗ୍ରୀ 'କମ୍' (୨୨% VWC) ଶ୍ରେଣୀରେ ଅଛି।" },
    { name: "ENSO (Nino 3.4) ସଙ୍କେତ", desc: "ସକାରାତ୍ମକ ENSO ବିଚ୍ୟାସ (+0.8°C) ପୂର୍ବୀୟ ଭାରତ ଉପରେ ୱାକର ପରିସଂଚରଣକୁ ଦବାଏ।" },
    { name: "ଐତିହାସିକ ସମାନ ପ୍ୟାଟର୍ଣ୍ଣ", desc: "ଜଳବାୟୁ ବିଜ୍ଞାନ ସମାନ ମିଳାନ ଦର୍ଶାଏ ଯେ ୫ ରୁ ୪ ସମାନ ବର୍ଷରେ ୭+ ଦିନର ଶୁଷ୍କ କାଳ ଥିଲା।" },
    { name: "MJO ପ୍ରାଣ ସଂଶୋଧନ", desc: "MJO ପ୍ରାଣ ୪ ରେ ଅନ୍ତରାଳିକ ବର୍ଷା ପ୍ରଦାନ କରେ।" }
  ],

  notifTitle: "ଚାଷୀ ସୂଚନା ଓ ସତର୍କତା ପ୍ରସାରଣ କେନ୍ଦ୍ର",
  notifDesc: "ବ୍ଲକ୍ କୃଷି ଅଧିକାରୀଙ୍କ ପାଇଁ ବହୁ-ଚ୍ୟାନେଲ୍ (SMS, WhatsApp, Voice OBD) ପ୍ରସାରଣ ଗେଟୱେ",
  notifRefresh: "ଡିଲିଭରୀ ଲଗ୍ ରିଫ୍ରେସ୍ କରନ୍ତୁ",
  notifSubscribers: "ମୋଟ ସଦସ୍ୟ",
  notifActive: "ସକ୍ରିୟ",
  notifDelivered: "ସଫଳତାର ସହ ଡିଲିଭର",
  notifFailed: "ବିଫଳ / ଅପହଞ୍ଚ",
  notifTotalBroadcasts: "ମୋଟ ପ୍ରସାରଣ",
  notifAcross: "୧୦ ଜିଲ୍ଲାରେ",
  notifCompose: "ବ୍ଲକ୍ ପରାମର୍ଶ ଲେଖନ୍ତୁ ଓ ପ୍ରସାରିତ କରନ୍ତୁ",
  notifTarget: "ଲକ୍ଷ୍ୟ",
  notifChannel: "ପ୍ରସାରଣ ଚ୍ୟାନେଲ୍:",
  notifChannels: ["WhatsApp ଓ SMS", "କେବଳ SMS", "କେବଳ WhatsApp", "Voice OBD ପ୍ରସାରଣ"],
  notifMultiLang: "ବହୁଭାଷୀ ପ୍ରସାରଣ ସାମଗ୍ରୀ:",
  notifSend: "କୁ ପ୍ରସାରଣ ପଠାନ୍ତୁ",
  notifEstReach: "ଆଶା ପହଁଚ: ୫,୨୪୦ ପଞ୍ଜୀକୃତ ଚାଷୀ",
  notifHandset: "ଚାଷୀ ହ୍ୟାଣ୍ଡସେଟ୍ ପୂର୍ବାବଲୋକନ",
  notifDelivered2: "ଡିଲିଭର ହୋଇଗଲା",
  notifLogs: "ସାମ୍ପ୍ରତିକ ପ୍ରସାରଣ ଲଗ୍ ଓ ଅଡିଟ୍ ଟ୍ରେଲ୍",
  notifBroadcastId: "ପ୍ରସାରଣ ID",
  notifLocation: "ସ୍ଥାନ",
  notifChannel2: "ଚ୍ୟାନେଲ୍",
  notifSent: "ପଠାଗଲା",
  notifDelivered3: "ଡିଲିଭର",
  notifFailed2: "ବିଫଳ",
  notifStatus: "ସ୍ଥିତି",

  sysTitle: "ସିଷ୍ଟମ୍ ସ୍ୱାସ୍ଥ୍ୟ ଓ ଅପରେସନାଲ୍ ସ୍ଥିତି",
  sysDesc: "ମୌସୁମ ବିଜ୍ଞାନ ଇନ୍‌ଜେସ୍ଟନ ପାଇପଲାଇନ୍, ML ସେବା ଓ ପ୍ରସାରଣ ଗେଟୱେର ବାସ୍ତବ-ସମୟ ନିଦାନ",
  sysAllOk: "ସମସ୍ତ ମୁଖ୍ୟ ଉପ-ପ୍ରଣାଳୀ ଅପରେସନାଲ୍",
  sysWeather: "ପାଣିପାଗ ତଥ୍ୟ ଇନ୍‌ଜେସ୍ଟନ",
  sysClimate: "ଜଳବାୟୁ ସଙ୍କେତ",
  sysML: "ML ପୂର୍ବାନୁମାନ ଇଞ୍ଜିନ୍",
  sysLastRun: "ଶେଷ ମଡେଲ୍ ରନ୍",
  sysAvail: "ଉପଲବ୍ଧ",
  sysOperational: "ଅପରେସନାଲ୍",
  sysTableTitle: "ଉପ-ପ୍ରଣାଳୀ ଓ API ବିଳମ୍ବ ଟେଲିମେଟ୍ରୀ",
  sysComponent: "ଉପ-ପ୍ରଣାଳୀ ଉପାଦାନ",
  sysType: "ପ୍ରକାର",
  sysStatus: "ସ୍ଥିତି",
  sysLatency: "ପ୍ରତିକ୍ରିୟା ବିଳମ୍ବ",
  sysGovernance: "ପ୍ରୋଟୋଟାଇପ୍ ଅଖଣ୍ଡତା ଓ ବୈଜ୍ଞାନିକ ଶାସନ ସୂଚନା",
  sysGovernanceDesc: "ଏହି ପ୍ରଣାଳୀ ସ୍ମାର୍ଟ ଇଣ୍ଡିଆ ହ୍ୟାକାଥନ୍ (SIH ୨୦୨୬) ପାଇଁ ବିକଶିତ ଏକ ଇଞ୍ଜିନିୟରିଂ କାର୍ଯ୍ୟଶୀଳ ପ୍ରଦର୍ଶନ ପ୍ରୋଟୋଟାଇପ୍।",

  fmAppTitle: "ମୌସୁମୀ ସାଥୀ",
  appTitle: "ମୌସୁମୀ ସାଥୀ",
  fmLocation: "ସ୍ଥାନ",
  location: "ସ୍ଥାନ",
  fmTodayAdvice: "ଆଜିର ଚାଷ ପରାମର୍ଶ",
  todayAdvice: "ଆଜିର ଚାଷ ପରାମର୍ଶ",
  fmSowingRisk: "ବୁଣା ବିପଦ",
  sowingRisk: "ବୁଣା ବିପଦ",
  fmDrySpellRisk: "ଶୁଷ୍କ କାଳ ବିପଦ",
  drySpellRisk: "ଶୁଷ୍କ କାଳ ବିପଦ",
  fmRainfallStatus: "ବର୍ଷା ସ୍ଥିତି",
  rainfallStatus: "ବର୍ଷା ସ୍ଥିତି",
  fmMyCrop: "ମୋର ଫସଲ",
  myCrop: "ମୋର ଫସଲ",
  fmForecast7d: "୭ ଦିନିଆ ଅନୁମାନ",
  forecast7d: "୭ ଦିନିଆ ଅନୁମାନ",
  fmAudioListen: "ପରାମର୍ଶ ଶୁଣନ୍ତୁ",
  audioListen: "ପରାମର୍ଶ ଶୁଣନ୍ତୁ",
  fmAudioPlaying: "ପରାମର୍ଶ ଚାଲିଛି...",
  audioPlaying: "ପରାମର୍ଶ ଚାଲିଛି...",
  fmCallHelpline: "କିଷାନ ହେଲ୍ପଲାଇନକୁ କଲ କରନ୍ତୁ (1800-180-1551)",
  callKisanHelpline: "କିଷାନ ହେଲ୍ପଲାଇନକୁ କଲ କରନ୍ତୁ (1800-180-1551)",
  fmCaution: "ତୁରନ୍ତ ଧାନ ବୁଣା କାର୍ଯ୍ୟ କରନ୍ତୁ ନାହିଁ। ଆଗାମୀ ଦିନରେ ବର୍ଷା ଅନିୟମିତ ରହିପାରେ।",
  cautionMessage: "ତୁରନ୍ତ ଧାନ ବୁଣା କାର୍ଯ୍ୟ କରନ୍ତୁ ନାହିଁ। ଆଗାମୀ ଦିନରେ ବର୍ଷା ଅନିୟମିତ ରହିପାରେ।",
  fmProceed: "ନିୟମିତ ବର୍ଷାର ଅନୁକୂଳ ସମ୍ଭାବନା ଅଛି। ଆପଣ ଧାନ ତଳି ପକାଇବା ଓ ଜମି ପ୍ରସ୍ତୁତି କାର୍ଯ୍ୟ ଆଗେଇ ନେଇପାରିବେ।",
  proceedMessage: "ନିୟମିତ ବର୍ଷାର ଅନୁକୂଳ ସମ୍ଭାବନା ଅଛି। ଆପଣ ଧାନ ତଳି ପକାଇବା ଓ ଜମି ପ୍ରସ୍ତୁତି କାର୍ଯ୍ୟ ଆଗେଇ ନେଇପାରିବେ।",
  fmDrainage: "ପ୍ରବଳ ବର୍ଷା ସତର୍କତା! ଜମିରୁ ଅତିରିକ୍ତ ପାଣି ନିଷ୍କାସନ ନାଳି ତୁରନ୍ତ ସଫା କରନ୍ତୁ।",
  drainageMessage: "ପ୍ରବଳ ବର୍ଷା ସତର୍କତା! ଜମିରୁ ଅତିରିକ୍ତ ପାଣି ନିଷ୍କାସନ ନାଳି ତୁରନ୍ତ ସଫା କରନ୍ତୁ।",
  fmIrrigation: "ଶୁଷ୍କ ପାଗର ସମ୍ଭାବନା। ପମ୍ପସେଟ୍ କିମ୍ବା ପୋଖରୀରୁ ହାଲୁକା ଜଳସେଚନ ବ୍ୟବସ୍ଥା କରନ୍ତୁ।",
  irrigationMessage: "ଶୁଷ୍କ ପାଗର ସମ୍ଭାବନା। ପମ୍ପସେଟ୍ କିମ୍ବା ପୋଖରୀରୁ ହାଲୁକା ଜଳସେଚନ ବ୍ୟବସ୍ଥା କରନ୍ତୁ।",
  high: "ଅଧିକ",
  moderate: "ମଧ୍ୟମ",
  disclaimer: "ଅଫିସିଆଲ୍ MoES/IMD ଡାଟା ଷ୍ଟ୍ରିମ୍",

  authTitle: "MoES ମୌସୁମୀ ଇଣ୍ଟେଲ୍",
  authSubtitle: "ଆପଣଙ୍କ ମୋବାଇଲରେ କ୍ଲାଉଡ୍ ସତର୍କତା ଓ ପାଣିପାଗ ଅପଡେଟ୍",
  authSignIn: "ସାଇନ୍ ଇନ୍",
  authCreateAccount: "ଖାତା ତିଆରି କରନ୍ତୁ",
  authName: "ନାମ",
  authPassword: "ପାସୱାର୍ଡ",
  authMobile: "ମୋବାଇଲ୍ ନମ୍ବର",
  authPincode: "ଅଞ୍ଚଳ ପିନକୋଡ୍",
  authAutoDetect: "ସ୍ୱୟଂ ଚିହ୍ନଟ",
  authDetecting: "ଚିହ୍ନଟ କରୁଛି...",
  authNewFarmer: "ନୂଆ ଚାଷୀ?",
  authAlready: "ପୂର୍ବରୁ ପଞ୍ଜୀକୃତ?",
  authCreateOne: "ଖାତା ତିଆରି କରନ୍ତୁ",
  authSignin: "ସାଇନ୍ ଇନ୍",
  authWeatherAlerts: "SMS ମାଧ୍ୟମରେ ପାଣିପାଗ ସତର୍କତା",
  authSecured: "MoES ସୁରକ୍ଷିତ",

  rice: "ଧାନ (Paddy)",
  maize: "ମକା",
  groundnut: "ଚିନାବାଦାମ",
  pulses: "ଡାଲି ଜାତୀୟ",
  vegetables: "ପରିବା ଚାଷ",
  cotton: "କପା",

  mm: "mm",
  percent: "%",
  block: "ବ୍ଲକ୍",
  district: "ଜିଲ୍ଲା",
  days: "ଦିନ",
  listen: "ଶୁଣନ୍ତୁ",
  playing: "ଚାଲିଛି...",
};

export const translations = { en, hi, or };
