/**
 * Multi-lingual Localization Dictionary (English, Hindi, Odia)
 * Standardized for Farmer Mode and Decision Support
 */

export const translations = {
  en: {
    appTitle: "Monsoon Saathi",
    appSubtitle: "AI-Powered Hyperlocal Weather & Crop Advisory",
    officerDashboard: "Officer Command Center",
    farmerMode: "Farmer Mode",
    changeLanguage: "Language",
    location: "Location",
    selectBlock: "Select Block",
    todayAdvice: "Today's Agricultural Advice",
    sowingRisk: "Sowing Risk",
    drySpellRisk: "Dry Spell Risk",
    onsetProbability: "Onset Probability",
    heavyRainRisk: "Heavy Rain Risk",
    rainfallStatus: "Rainfall Outlook",
    soilMoisture: "Soil Moisture",
    expectedRain: "Expected Rain",
    confidence: "Forecast Confidence",
    myCrop: "My Crop",
    forecast7d: "7-Day Outlook",
    fullAdvisory: "Full Advisory",
    audioListen: "Listen to Advice",
    audioPlaying: "Playing Audio...",
    actionsToTake: "Recommended Actions:",
    whyThisAdvice: "Why This Recommendation?",
    low: "LOW",
    moderate: "MODERATE",
    high: "HIGH",
    veryHigh: "VERY HIGH",
    rice: "Rice (Paddy)",
    maize: "Maize",
    groundnut: "Groundnut",
    pulses: "Pulses",
    vegetables: "Vegetables",
    cotton: "Cotton",
    cautionMessage: "Do not sow rice immediately. Rainfall may remain irregular over the coming days. Keep irrigation available and monitor the next forecast update.",
    proceedMessage: "Good rainfall continuity expected. You may proceed with nursery sowing and field preparation.",
    drainageMessage: "Heavy rainfall alert! Clear drainage bunds immediately to protect standing nursery seedlings.",
    irrigationMessage: "Dry spell developing. Arrange protective irrigation from borewells or farm ponds.",
    callKisanHelpline: "Call Kisan Helpline (1800-180-1551)",
    disclaimer: "Prototype Forecast - Ministry of Earth Sciences (MoES / NCMRWF)"
  },
  hi: {
    appTitle: "मानसून साथी",
    appSubtitle: "एआई आधारित ब्लॉक स्तरीय मौसम व फसल परामर्श",
    officerDashboard: "कमांड सेंटर",
    farmerMode: "किसान सेवा (Farmer Mode)",
    changeLanguage: "भाषा बदलें",
    location: "स्थान",
    selectBlock: "ब्लॉक चुनें",
    todayAdvice: "आज की कृषि सलाह",
    sowingRisk: "बुवाई जोखिम",
    drySpellRisk: "सूखा/शुष्क दौर जोखिम",
    onsetProbability: "मानसून आगमन संभावना",
    heavyRainRisk: "भारी बारिश जोखिम",
    rainfallStatus: "वर्षा अनुमान",
    soilMoisture: "मिट्टी की नमी",
    expectedRain: "अनुमानित वर्षा",
    confidence: "अनुमान सटीकता",
    myCrop: "मेरी फसल",
    forecast7d: "7-दिवसीय अनुमान",
    fullAdvisory: "विस्तृत परामर्श",
    audioListen: "सलाह सुनें",
    audioPlaying: "सलाह सुनाई जा रही है...",
    actionsToTake: "सुझाए गए कृषि कार्य:",
    whyThisAdvice: "यह सलाह क्यों दी गई?",
    low: "कम (Low)",
    moderate: "मध्यम (Moderate)",
    high: "अधिक (High)",
    veryHigh: "अत्यधिक (Very High)",
    rice: "धान (चावल)",
    maize: "मक्का",
    groundnut: "मूंगफली",
    pulses: "दालें (अरहर/मूंग)",
    vegetables: "सब्जियां",
    cotton: "कपास",
    cautionMessage: "धान की बुवाई तुरंत न करें। आने वाले दिनों में वर्षा अनियमित रह सकती है। सिंचाई के साधन तैयार रखें और अगले मौसम पूर्वानुमान की प्रतीक्षा करें।",
    proceedMessage: "अनुकूल वर्षा की संभावना है। आप धान की नर्सरी की बुवाई और खेत की तैयारी शुरू कर सकते हैं।",
    drainageMessage: "भारी वर्षा की चेतावनी! खेत से अतिरिक्त जल निकासी की तुरंत व्यवस्था करें ताकि नर्सरी न डूबे।",
    irrigationMessage: "शुष्क दौर की संभावना। खेत में जीवनरक्षक हल्की सिंचाई का प्रबंध रखें।",
    callKisanHelpline: "किसान हेल्पलाइन पर कॉल करें (1800-180-1551)",
    disclaimer: "प्रोटोटाइप पूर्वानुमान - पृथ्वी विज्ञान मंत्रालय (MoES / NCMRWF)"
  },
  or: {
    appTitle: "ମୌସୁମୀ ସାଥୀ",
    appSubtitle: "ବ୍ଲକ ସ୍ତରୀୟ ଏଆଇ ପାଣିପାଗ ଓ କୃଷି ପରାମର୍ଶ",
    officerDashboard: "କମାଣ୍ଡ ସେଣ୍ଟର",
    farmerMode: "ଚାଷୀ ମୋଡ଼ (Farmer Mode)",
    changeLanguage: "ଭାଷା ବଦଳାନ୍ତୁ",
    location: "ସ୍ଥାନ",
    selectBlock: "ବ୍ଲକ ବାଛନ୍ତୁ",
    todayAdvice: "ଆଜିର ଚାଷ ପରାମର୍ଶ",
    sowingRisk: "ବୁଣା ବିପଦ",
    drySpellRisk: "ଶୁଷ୍କ ପାଗ ବିପଦ",
    onsetProbability: "ମୌସୁମୀ ଆଗମନ ସମ୍ଭାବନା",
    heavyRainRisk: "ପ୍ରବଳ ବର୍ଷା ବିପଦ",
    rainfallStatus: "ବର୍ଷା ସ୍ଥିତି",
    soilMoisture: "ମାଟିର ଆର୍ଦ୍ରତା",
    expectedRain: "ଆଶା କରାଯାଉଥିବା ବର୍ଷା",
    confidence: "ପୂର୍ବାନୁମାନ ନିର୍ଭରଯୋଗ୍ୟତା",
    myCrop: "ମୋର ଫସଲ",
    forecast7d: "୭ ଦିନିଆ ପାଣିପାଗ",
    fullAdvisory: "ସମ୍ପୂର୍ଣ୍ଣ ପରାମର୍ଶ",
    audioListen: "ପରାମର୍ଶ ଶୁଣନ୍ତୁ",
    audioPlaying: "ପରାମର୍ଶ ଚାଲିଛି...",
    actionsToTake: "କୃଷକମାନଙ୍କ ପାଇଁ କରଣୀୟ ପଦକ୍ଷେପ:",
    whyThisAdvice: "ଏହି ପରାମର୍ଶ କାହିଁକି ଦିଆଗଲା?",
    low: "ସ୍ୱଳ୍ପ (Low)",
    moderate: "ମଧ୍ୟମ (Moderate)",
    high: "ଅଧିକ (High)",
    veryHigh: "ଅତ୍ୟଧିକ (Very High)",
    rice: "ଧାନ (Paddy)",
    maize: "ମକା",
    groundnut: "ଚିନାବାଦାମ",
    pulses: "ଡାଲି ଜାତୀୟ (ମୁଗ/ହରଡ଼)",
    vegetables: "ପରିବା ଚାଷ",
    cotton: "କପା",
    cautionMessage: "ତୁରନ୍ତ ଧାନ ବୁଣା କାର୍ଯ୍ୟ କରନ୍ତୁ ନାହିଁ। ଆଗାମୀ ଦିନରେ ବର୍ଷା ଅନିୟମିତ ରହିପାରେ। ଜଳସେଚନ ପ୍ରସ୍ତୁତ ରଖନ୍ତୁ ଏବଂ ପରବର୍ତ୍ତୀ ପାଣିପାଗ ସୂଚନାକୁ ଅପେକ୍ଷା କରନ୍ତୁ।",
    proceedMessage: "ନିୟମିତ ବର୍ଷାର ଅନୁକୂଳ ସମ୍ଭାବନା ଅଛି। ଆପଣ ଧାନ ତଳି ପକାଇବା ଓ ଜମି ପ୍ରସ୍ତୁତି କାର୍ଯ୍ୟ ଆଗେଇ ନେଇପାରିବେ।",
    drainageMessage: "ପ୍ରବଳ ବର୍ଷା ସତର୍କତା! ଜମିରୁ ଅତିରିକ୍ତ ପାଣି ନିଷ୍କାସନ ନାଳି ତୁରନ୍ତ ସଫା କରନ୍ତୁ।",
    irrigationMessage: "ଶୁଷ୍କ ପାଗର ସମ୍ଭାବନା। ପମ୍ପସେଟ୍ କିମ୍ବା ପୋଖରୀରୁ ହାଲୁକା ଜଳସେଚନ ବ୍ୟବସ୍ଥା କରନ୍ତୁ।",
    callKisanHelpline: "କିଷାନ ହେଲ୍ପଲାଇନକୁ କଲ କରନ୍ତୁ (1800-180-1551)",
    disclaimer: "ପ୍ରୋଟୋଟାଇପ୍ ପୂର୍ବାନୁମାନ - ପୃଥିବୀ ବିଜ୍ଞାନ ମନ୍ତ୍ରଣାଳୟ (MoES / NCMRWF)"
  }
};
